name: Build SQLite3

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: macos-13
            platform: macos
            arch: x64
          - os: windows-latest
            platform: windows
            arch: x64

    steps:
      - name: Download SQLite3 source
        run: |
          curl -o sqlite.tar.gz https://sqlite.org/2025/sqlite-autoconf-3500100.tar.gz
          tar -xzf sqlite.tar.gz
          mv sqlite-autoconf-3500100 sqlite
        shell: bash

      # - name: Setup MSVC (Windows)
      #   if: matrix.platform == 'windows'
      #   uses: microsoft/setup-msbuild@v1.1

      - name: Build SQLite3 (Unix/Mac)
        if: matrix.platform != 'windows'
        run: |
          cd sqlite
          ./configure
          make

      - name: Build SQLite3 (Windows)
        if: matrix.platform == 'windows'
        shell: cmd
        run: |
          cd sqlite
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /f Makefile.msc

      - name: Upload Libraries Windows
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: sqlite3-windows-${{ matrix.arch }}
          path: |
            sqlite/sqlite3.def
            sqlite/sqlite3.lib
            sqlite/sqlite3.dll

      - name: Upload Libraries Mac
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v4
        with:
          name: sqlite3-mac-${{ matrix.arch }}
          path: |
            sqlite/libsqlite3.a
            sqlite/libsqlite3.dylib

      - name: Upload Libraries Linux
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: sqlite3-linux-${{ matrix.arch }}
          path: |
            sqlite/libsqlite3.a
            sqlite/libsqlite3.so
