name: Build SQLite3

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact: libsqlite3.so
          - os: macos-latest
            platform: macos
            artifact: libsqlite3.dylib
          - os: windows-latest
            platform: windows
            artifact: sqlite3.dll

    steps:
      - name: Download SQLite3 source
        run: |
          curl -o sqlite.tar.gz https://sqlite.org/2025/sqlite-autoconf-3500100.tar.gz
          tar -xzf sqlite.tar.gz
          mv sqlite-autoconf-3500100 sqlite
        shell: bash

      # - name: Setup MSVC (Windows)
      #   if: matrix.platform == 'windows'
      #   uses: microsoft/setup-msbuild@v1.1

      - name: Build SQLite3 (Unix/Mac)
        if: matrix.platform != 'windows'
        run: |
          cd sqlite
          ./configure
          make

      - name: Build SQLite3 (Windows)
        if: matrix.platform == 'windows'
        shell: cmd
        run: |
          cd sqlite
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /f Makefile.msc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sqlite3-${{ matrix.platform }}
          path: |
            sqlite/.libs/libsqlite3.so*
            sqlite/.libs/libsqlite3.dylib*
            sqlite/sqlite3.dll
